from typing import List, Literal

from pydantic import BaseModel


class Inference(BaseModel):
    username: str
    document: str
    image: str


class Account(BaseModel):
    username: str
    password: str


class Report(BaseModel):
    username: str
    symptomStr: str
    reportTime: float
    type_: Literal["cv", "nlp"]
    prognosis: List[str]
    probability: List[str]
    image: str


class SymptomsChecklist(BaseModel):
    abdominal_pain: int
    abnormal_menstruation: int
    acidity: int
    acute_liver_failure: int
    altered_sensorium: int
    anxiety: int
    back_pain: int
    belly_pain: int
    blackheads: int
    bladder_discomfort: int
    blister: int
    blood_in_sputum: int
    bloody_stool: int
    blurred_and_distorted_vision: int
    breathlessness: int
    brittle_nails: int
    bruising: int
    burning_micturition: int
    chest_pain: int
    chills: int
    cold_hands_and_feets: int
    coma: int
    congestion: int
    constipation: int
    continuous_feel_of_urine: int
    continuous_sneezing: int
    cough: int
    cramps: int
    dark_urine: int
    dehydration: int
    depression: int
    diarrhoea: int
    dischromic_patches: int
    distention_of_abdomen: int
    dizziness: int
    drying_and_tingling_lips: int
    enlarged_thyroid: int
    excessive_hunger: int
    extra_marital_contacts: int
    family_history: int
    fast_heart_rate: int
    fatigue: int
    fluid_overload: int
    foul_smell_of_urine: int
    headache: int
    high_fever: int
    hip_joint_pain: int
    history_of_alcohol_consumption: int
    increased_appetite: int
    indigestion: int
    inflammatory_nails: int
    internal_itching: int
    irregular_sugar_level: int
    irritability: int
    irritation_in_anus: int
    itching: int
    joint_pain: int
    knee_pain: int
    lack_of_concentration: int
    lethargy: int
    loss_of_appetite: int
    loss_of_balance: int
    loss_of_smell: int
    malaise: int
    mild_fever: int
    mood_swings: int
    movement_stiffness: int
    mucoid_sputum: int
    muscle_pain: int
    muscle_wasting: int
    muscle_weakness: int
    nausea: int
    neck_pain: int
    nodal_skin_eruptions: int
    obesity: int
    pain_behind_the_eyes: int
    pain_during_bowel_movements: int
    pain_in_anal_region: int
    painful_walking: int
    palpitations: int
    passage_of_gases: int
    patches_in_throat: int
    phlegm: int
    polyuria: int
    prominent_veins_on_calf: int
    puffy_face_and_eyes: int
    pus_filled_pimples: int
    receiving_blood_transfusion: int
    receiving_unsterile_injections: int
    red_sore_around_nose: int
    red_spots_over_body: int
    redness_of_eyes: int
    restlessness: int
    runny_nose: int
    rusty_sputum: int
    scurring: int
    shivering: int
    silver_like_dusting: int
    sinus_pressure: int
    skin_peeling: int
    skin_rash: int
    slurred_speech: int
    small_dents_in_nails: int
    spinning_movements: int
    spotting_urination: int
    stiff_neck: int
    stomach_bleeding: int
    stomach_pain: int
    sunken_eyes: int
    sweating: int
    swelled_lymph_nodes: int
    swelling_joints: int
    swelling_of_stomach: int
    swollen_blood_vessels: int
    swollen_extremeties: int
    swollen_legs: int
    throat_irritation: int
    toxic_look_typhos: int
    ulcers_on_tongue: int
    unsteadiness: int
    visual_disturbances: int
    vomiting: int
    watering_from_eyes: int
    weakness_in_limbs: int
    weakness_of_one_body_side: int
    weight_gain: int
    weight_loss: int
    yellow_crust_ooze: int
    yellow_urine: int
    yellowing_of_eyes: int
    yellowish_skin: int
