version: '3'
services:

  frontend:
    build:
      context: ../hackathon_submission/frontend/
      dockerfile: Dockerfile
    ports:
      - 8501:5001
    volumes:
      - DiagnoEase:/DiagnoEase/frontend
    restart: on-failure

  backend:
    build:
      context: ../hackathon_submission/backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5002
    volumes:
      - DiagnoEase:/DiagnoEase/backend
    restart: on-failure
